# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build angular frontend'
  workingDirectory: $(ng-working-dir)
  

- script: |
    npm install
    npm run build
  displayName: 'npm install and build keystone cms'
  workingDirectory: $(keystone-working-dir)

- task: ArchiveFiles@2
  displayName: 'Archive angular app'
  inputs:
    rootFolderOrFile: '$(ng-working-dir)/dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    

- task: PublishBuildArtifacts@1
  displayName: 'Publish build angular app'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: angularBuildArtifact
  