version: '3.7'
services:
  cfg-cms:
    image: cfg-cms
    volumes:
      - ./cfg-cms:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: "keystone-next build && keystone-next prisma migrate deploy"
  cfg-frontend:
    image: cfg-frontend
    volumes:
      - ./cfg-frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: "ng serve --port 4200 --host 0.0.0.0 --public-host=\"http://0.0.0.0:4200\" --base-href /two/ --disable-host-check"
  do-nginx:
    image: do-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]
    links:
      - cfg-cms
      - cfg-frontend