version: "3.7"

volumes:
  cfgdata:
    driver: azure_file
    driver_opts:
      share_name: cfgfileshare
      storage_account_name: cfgstorage

services:
  cfg-postgres:
    image: acrcfg.azurecr.io/postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    volumes:
      - cfgdata:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1ch@fdog31
      - APP_DB_NAME=cfg-keystone-db
      - APP_DB_USER=cfg-keystone-db-admin
      - APP_DB_PASS=1ch@fdog33
  
  cfg-backend:
    build: 
      args:
        - NODE_ENV=development
      context: ./chefdog.keystone
      dockerfile: Dockerfile
    image: acrcfg.azurecr.io/chefdog-keystone
    command: npm run start
    environment:
      - DATABASE_HOST=cfg-postgres
      - DATABASE_NAME=cfg-keystone-db
      - DATABASE_USER=cfg-keystone-db-admin
      - DATABASE_PASSWORD=1ch@fdog33 
      - DATABASE_PORT=5432
    ports: 
      - 3000:3000
    links:
      - cfg-postgres
    depends_on:
      - cfg-postgres

  cfg-frontend:
    build: 
      args:
        - NODE_ENV=development
      context: ./chefdog.frontend
      dockerfile: Dockerfile
    image: acrcfg.azurecr.io/chefdog-frontend
    command: npm run start    
    ports: 
      - 3500:3500
    links:
      - cfg-backend
    depends_on:
      - cfg-backend

 
    