FROM nginx:alpine

RUN apk add --update nodejs nodejs-npm \
    && npm install -g @angular/cli \
    && npm install

WORKDIR /app

COPY cfg-cms ./cfg-cms
COPY cfg-frontend ./cfg-frontend

RUN rm -rf /usr/share/nginx/html/*

RUN cd cfg-cms \
    && npm ci \
    && npm run build:docker \
    && cd ..

RUN cd cfg-frontend \
    && npm ci \
    && npm run build:docker \
    && cd ..

EXPOSE 80